Multi task
JetBrains-Research/tasktracker-3 pull request #24
Opened 2023-08-04 13:54 UTC by mikrise2

Support of multi task selection

2023-08-04 15:16 UTC, TitovSergey commented
I see here two problems from start:
- Links color is not very good let's change it to the shades of grey. 
for example:
```
/* unvisited link */
a:link {
  color: #808080;
}

/* visited link */
a:visited {
  color: #696969;
}
```

- currently we don't return to the original state of the project after we press "submit button".  WHile it is not in the scope of this PR, it could be next task [ML4SE-112]

2023-08-07 08:57 UTC, nbirillo commented on src/main/kotlin/org/jetbrains/research/tasktracker/config/content/TaskContentConfig.kt
> +    val focusFileId: String? = null
What is it? Please, add a description

2023-08-07 08:58 UTC, nbirillo commented
Let's discuss big issues in dm

2023-08-08 13:20 UTC, nbirillo requested changes

2023-08-09 08:52 UTC, merged